// Full content dictionary, ported verbatim from the high-fidelity reference
// design (ref/sytle12-claude-design/index.html). Keyed by Nuxt i18n locale
// codes ('zh' | 'en'). Structured arrays/objects are read directly from here
// instead of through vue-i18n message functions.

export const GP_CONTENT = {
  zh: {
    locale: '简体中文',
    promo: {
      tag: '2026 年中大促',
      title: '充 $50 起享赠送',
      body: '充 $100 得 $120，充 $1000 得 $1300，最高赠 30%',
      cta: '立即领取',
      countdown: '活动至 6.30 (UTC+0)',
    },
    nav: {
      home: '首页', product: '产品', features: '功能特性', scenarios: '应用场景',
      pricing: '价格套餐', specs: '性能规格', customers: '客户案例',
      download: '下载', blog: '博客', help: '帮助中心', resources: '资源', docs: '帮助文档', faq: '常见问题', apiDocs: 'API 文档', news: '新闻动态',
      login: '登录', signup: '免费注册', trial: '免费试用',
      console: '控制台', logout: '退出登录', account: '账户',
    },
    hero: {
      tag: '海外营销 · 跨境电商 · 多账号矩阵',
      title1: '一人千号', titleHL: '云端运营', title2: '如同本地',
      sub: '为海外社媒、跨境电商团队打造的云手机平台。独立 IP、独立设备指纹、24 小时在线，让你的 TikTok、WhatsApp、Shopee 矩阵稳定运转。',
      cta1: '免费试用', cta2: '查看演示',
      trust1: '全球 22 个节点', trust2: '原生 ARM 性能', trust3: '金融级数据隔离',
    },
    stats: {
      devices: '在线云手机', devicesL: '全球同时在线',
      users: '企业客户', usersL: '覆盖 60+ 国家',
      uptime: '服务可用性', uptimeL: 'SLA 99.99%',
      ips: '独立出口 IP', ipsL: '可分配纯净 IP 池',
    },
    logos: '受信于全球团队',
    features: {
      eyebrow: '为何选择 Gloryphone',
      title: '一台手机做不到的，云手机一次给你',
      sub: '原生 Android 系统，云端集群运行。每一台都是真实硬件指纹、真实设备 ID、独立网络环境。',
      items: [
        { t: '独立设备指纹', d: 'IMEI、Android ID、MAC、机型、序列号每台独一无二，规避平台关联检测。' },
        { t: '纯净住宅 IP', d: '支持 60+ 国家住宅级出口 IP，可绑定到指定云手机长期使用，IP 与账号 1:1。' },
        { t: 'ARM 原生算力', d: '基于 ARM 服务器原生运行 Android，无需翻译层，性能逼近真机。' },
        { t: '24 小时托管', d: '云端常驻，离线挂机不掉号；自动任务、定时唤醒、关机重启全自动。' },
        { t: '团队协作', d: '子账号权限、设备分组、操作日志审计，支持多人同时管理同一矩阵。' },
        { t: 'OpenAPI 集成', d: 'RESTful API + Webhook，对接 RPA、自动化脚本、自有运营平台。' },
      ],
    },
    spotlight: {
      eyebrow: '云控台',
      title: '可视化批量操控，千台如同一台',
      sub: '在浏览器里同时看到上百台设备的实时画面。一键群控、模板化任务、跨设备同步操作。',
      bullets: [
        '网页直接预览与控制，无需安装客户端',
        '屏幕复制：1 台主控同步到 N 台从机',
        '脚本录制 → 一键回放到指定分组',
        '异常自动告警，掉线自动重连',
      ],
      more: '了解更多',
    },
    scenarios: {
      eyebrow: '应用场景', title: '你的业务，我们都跑过',
      tabs: ['跨境电商', '社媒矩阵', '游戏挂机', '测试与开发', '企业办公'],
      panels: [
        { t: '亚马逊 / Shopee / TikTok Shop 多店铺', d: '每店铺一个独立设备 + 独立 IP，永久绑定。卖家可以一人同时管理 50+ 店铺，不再担心账号关联封号。',
          m: [['50+', '并发店铺'], ['0', '关联封号'], ['6', '全球区域']] },
        { t: 'TikTok / Instagram / Twitter 矩阵', d: '为每个 IP 形象建立专属环境，养号、发布、互动全流程在云端完成。账号留存率提升 3 倍。',
          m: [['1000+', '矩阵账号'], ['95%', '存活率'], ['24h', '云端在线']] },
        { t: '游戏多开 · 长线挂机', d: '原生 ARM 性能，主流手游流畅运行；公会任务、日常副本自动化，账号 24 小时不掉线。',
          m: [['60', 'FPS 稳定'], ['24h', '挂机不掉'], ['100+', '并发开图']] },
        { t: '应用测试 · 兼容性验证', d: '覆盖主流机型与 Android 版本，CI 集成 ADB 直连，回归自动化测试一晚跑完。',
          m: [['8-14', 'Android 版本'], ['120+', '机型库'], ['API', 'ADB / WDA']] },
        { t: 'BYOD · 移动办公', d: '员工自有设备无需安装企业 App，敏感数据 100% 留在云端，离职即收回访问权。',
          m: [['0', '数据落本地'], ['AES-256', '通信加密'], ['SSO', '企业目录']] },
      ],
    },
    compare: {
      eyebrow: '横向对比', title: '为什么团队从模拟器换到 Gloryphone',
      sub: '本地真机贵、模拟器假，云手机才是给团队的最优解。',
      cols: ['', '本地真机', 'PC 模拟器', '其他云服务', 'Gloryphone'],
      rows: [
        ['真实硬件指纹', '✓', '✗', '部分', '✓'],
        ['独立住宅 IP', '需自购', '需自购', '限速', '原生支持'],
        ['24 小时常驻', '需充电', '需开机', '✓', '✓'],
        ['批量管理', '极难', '麻烦', '支持', '可视化群控'],
        ['扩容速度', '天级', '小时级', '小时级', '秒级'],
        ['单台月成本', '￥30+', '￥10+', '￥18', '￥9 起'],
      ],
    },
    perf: {
      eyebrow: '性能', title: '真硬件，真性能',
      sub: '搭载自研 ARM 服务器节点，CPU、GPU、内存按设备隔离分配，无超售。',
      bars: [
        ['GeekBench 单核', 92], ['GeekBench 多核', 88], ['3DMark Wildlife', 80],
        ['AnTuTu 综合', 87], ['内存带宽', 95], ['I/O 读写', 91],
      ],
      stats: [
        ['8 核', 'ARM v9 物理核心'], ['12 GB', '独立内存'], ['1 Gbps', '出口带宽'], ['<30 ms', '全球延迟'],
      ],
    },
    pricing: {
      eyebrow: '价格', title: '按需付费，越用越省',
      sub: '钱包余额支付，分钟级开通；买得多、买得久更优惠，新购续费还送临时开机时长。',
      currency: '￥',
      badgeTrial: '新用户免费试用', badgeGift: '买席位送时长',
      ctaStart: '免费开始', ctaMore: '查看计费规则',
      fromLabel: '最低', unitMonth: '月', unitDay: '天', unitMinute: '分钟',
      perSeat: '台', perSlot: '个',
      resTitle: '三种资源，按需组合', resSub: '席位决定能造几台，包月开机数决定能同时跑几台，临时时长按分钟灵活补充。',
      seat: { name: '实例席位', desc: '决定可拥有的云手机实例数量，按月计费。', feats: ['1 席位 = 1 台云手机', '到期自动热迁移不中断', '可单台/批量续费', '数量越多单价越低'] },
      boot: { name: '包月开机数', desc: '决定可同时开机运行的实例数，按天计费。', feats: ['多实例轮流共享名额', '占名额运行不扣临时时长', '按天灵活购买', '适合错峰批量运营'] },
      rt: { name: '临时开机时长', desc: '按分钟计量，无使用期限，用完为止。', feats: ['开机满 1 分钟才计费', `每台每天封顶免超扣`, '随买随用、不过期', '名额满后自动回落扣时长'] },
      discEyebrow: '阶梯优惠', discTitle: '买多买久，越用越省', discSub: '数量阶梯折扣 × 时长折扣叠加，服务端实时计价。',
      discQtyHead: '数量越多越省', discDurHead: '时长越久越省', discPackHead: '买得越多越省',
      giftEyebrow: '专属福利', giftTitle: '每购买 1 个实例席位，每月赠送 {min} 分钟临时开机时长',
      giftDesc: '新购与续费都赠送，赠送量 = 每席位每月分钟数 × 席位数 × 月数，避免买了席位却开不了机。',
      giftExample: '例：续费 2 台 × 3 个月，立得 {total} 分钟临时开机时长',
      trialEyebrow: '0 元体验', trialTitle: '新用户免费试用', trialSub: '注册即领，先用后买，体验完整能力。', trialCta: '注册领取',
      subjSeat: '实例席位', subjBoot: '包月开机数', subjRuntime: '临时开机时长',
      daysWord: '天', minuteWord: '分钟', permanentWord: '永久',
      teaserMore: '查看完整价格',
    },
    testi: {
      eyebrow: '客户怎么说', title: '全球 8,000+ 团队的选择',
      items: [
        { name: 'Daniel L.', role: 'TikTok Shop 卖家 · 美国', text: '之前用模拟器频繁触发关联检测，换到 Gloryphone 之后 3 个月没有一个店铺被封。', initials: 'DL' },
        { name: '陈茜', role: 'MCN 运营总监 · 深圳', text: '矩阵 600 个 IG 账号，群控台一次点击全部更新主页 banner，省下了半个团队的人力。', initials: '陈' },
        { name: 'Mariko T.', role: 'Mobile QA Lead · 东京', text: '我们用 API 把 Gloryphone 接进了 CI/CD，凌晨自动跑回归，早上看报告，效率翻倍。', initials: 'MT' },
        { name: 'Ahmad K.', role: 'Web3 社区运营 · 迪拜', text: 'Discord & Twitter 矩阵管理终于不再被风控。住宅 IP 质量比我之前买的任何代理都干净。', initials: 'AK' },
        { name: '刘振', role: '游戏工作室 · 杭州', text: '150 台云手机挂《剑与远征》月卡号，月成本从 1.5w 降到 4k，回本周期 11 天。', initials: '刘' },
        { name: 'Sarah M.', role: '亚马逊大卖 · 伦敦', text: '客户经理半夜帮我解决 IP 切换问题，这种服务在欧洲根本找不到。', initials: 'SM' },
      ],
    },
    download: {
      eyebrow: '客户端', title: '随时随地，多端同步',
      sub: '网页端开箱即用；桌面 / 移动客户端提供更流畅的体验。',
      items: [
        { name: 'Windows', ver: 'v3.8.2 · 64-bit', size: '128 MB' },
        { name: 'macOS', ver: 'v3.8.2 · Universal', size: '142 MB' },
        { name: 'Android', ver: 'v3.8.0 · APK', size: '48 MB' },
        { name: 'iOS', ver: 'v3.7.5 · TestFlight', size: 'App Store' },
      ],
      btn: '立即下载',
    },
    blog: {
      eyebrow: '博客', title: '运营 · 技术 · 趋势',
      sub: '来自 Gloryphone 团队的实战经验、产品更新与跨境营销洞察。',
      all: '查看全部', readMore: '阅读全文', min: '分钟阅读', updated: '更新于',
      category: '分类', tags: '标签',
      empty: '暂无文章', error: '内容加载失败，请稍后重试', retry: '重试',
      prev: '上一页', next: '下一页',
    },
    docs: { updated: '最后更新' },
    faq: {
      eyebrow: '常见问题', title: '你可能想问',
      empty: '暂无常见问题', error: '内容加载失败，请稍后重试', retry: '重试', all: '全部',
    },
    feedback: {
      title: '这篇文档有帮助吗？',
      helpful: '有帮助', notHelpful: '没帮助',
      thanksVote: '感谢你的反馈！',
      reportTitle: '发现问题或有建议？',
      reportToggle: '留言反馈',
      placeholder: '描述你遇到的问题或建议……',
      contact: '联系方式（选填，方便我们回复你）',
      submit: '提交反馈', submitting: '提交中…',
      thanksFeedback: '已收到，感谢你的反馈！',
      emptyError: '请先填写反馈内容', error: '提交失败，请稍后重试',
    },
    cta: {
      title: '免费试用，看看云手机能为你做什么',
      sub: '无需信用卡，注册即用。',
      btn1: '立即免费试用', btn2: '预约演示',
    },
    footer: {
      desc: '为全球团队提供云端 ARM 算力与移动自动化基础设施。',
      cols: [
        { title: '产品', links: ['云手机', '群控台', 'OpenAPI', '客户端下载', '更新日志'] },
        { title: '解决方案', links: ['跨境电商', '社媒矩阵', '游戏挂机', '应用测试', '企业办公'] },
        { title: '资源', links: ['帮助中心', '开发者文档', '状态页', '博客', '新闻动态'] },
        { title: '公司', links: ['关于我们', '加入我们', '联系销售', '服务协议', '隐私政策'] },
      ],
      aiDocs: 'AI 文档',
      copy: '© 2026 Gloryphone Tech.  保留所有权利。',
      beian: '粤 ICP 备 2026000000 号-1',
    },
    cookies: {
      banner: {
        title: '我们重视你的隐私',
        body: '我们使用 Cookie 保障网站正常运行，并在你同意后用于分析与个性化营销。',
        accept: '全部接受',
        reject: '仅必要',
        customize: '自定义',
        manage: '管理偏好',
        learnMore: '了解更多',
      },
      prefs: {
        title: 'Cookie 偏好',
        save: '保存偏好',
        acceptAll: '全部接受',
        rejectAll: '全部拒绝',
        savedAt: '上次更新：{time}',
        notDecided: '尚未做出选择',
        alwaysOn: '始终启用',
      },
      categories: {
        necessary: { name: '必要', desc: '保障登录、安全与基本功能，无法关闭。' },
        functional: { name: '功能性', desc: '记住语言、主题等偏好，提升使用体验。' },
        analytics: { name: '分析', desc: '匿名统计访问数据，帮助我们改进产品。' },
        marketing: { name: '广告', desc: '用于衡量广告效果与跨站个性化推广。' },
      },
      policy: {
        title: 'Cookie 政策',
        updated: '最近更新：2026 年 6 月',
        intro: '本政策说明我们如何使用 Cookie 及类似技术，以及你如何管理偏好。',
        sections: [
          { h: '什么是 Cookie', p: 'Cookie 是网站存放在你设备上的小型文本文件，用于记住你的操作与偏好。' },
          { h: '我们的使用目的', p: '保障网站运行、记住偏好、统计分析，并在你同意后用于个性化营销。' },
          { h: '第三方与跨境', p: '部分分析与广告 Cookie 由第三方提供，数据可能在你所在地区之外处理。' },
          { h: '如何撤回同意', p: '你可随时在本页修改偏好，或清除浏览器 Cookie；撤回不影响此前处理的合法性。' },
          { h: '联系我们', p: '如对隐私有疑问，可通过页脚的联系方式与我们取得联系。' },
        ],
      },
    },
    theme: { color: '主题色', dark: '深色模式', light: '浅色模式', system: '跟随系统', language: '语言', appearance: '外观调节', accent: '配色', mode: '明暗' },
  },

  en: {
    locale: 'English',
    promo: {
      tag: '2026 Mid-Year Sale',
      title: 'Top up from $50',
      body: 'Recharge $100 get $120 · Recharge $1000 get $1300 · Up to +30%',
      cta: 'Claim now',
      countdown: 'Ends 6.30 (UTC+0)',
    },
    nav: {
      home: 'Home', product: 'Product', features: 'Features', scenarios: 'Use cases',
      pricing: 'Pricing', specs: 'Performance', customers: 'Customers',
      download: 'Download', blog: 'Blog', help: 'Help', resources: 'Resources', docs: 'Docs', faq: 'FAQ', apiDocs: 'API Docs', news: 'News',
      login: 'Sign in', signup: 'Sign up free', trial: 'Free trial',
      console: 'Console', logout: 'Sign out', account: 'Account',
    },
    hero: {
      tag: 'Overseas marketing · Cross-border e-commerce · Multi-account',
      title1: 'Run a thousand phones,', titleHL: 'from one browser tab', title2: '',
      sub: 'A cloud phone platform built for overseas social and e-commerce teams. Dedicated IP, unique device fingerprint, 24/7 online — keep your TikTok, WhatsApp and Shopee matrix running smoothly.',
      cta1: 'Start free trial', cta2: 'Watch demo',
      trust1: '22 global regions', trust2: 'Native ARM silicon', trust3: 'Bank-grade isolation',
    },
    stats: {
      devices: 'Online phones', devicesL: 'Concurrent worldwide',
      users: 'Business customers', usersL: 'Across 60+ countries',
      uptime: 'Service uptime', uptimeL: '99.99% SLA',
      ips: 'Dedicated IPs', ipsL: 'Clean residential pool',
    },
    logos: 'Trusted by teams worldwide',
    features: {
      eyebrow: 'Why Gloryphone',
      title: "Everything one phone can't do — solved.",
      sub: 'Native Android running on cloud ARM clusters. Each instance has its own hardware fingerprint, device ID and network.',
      items: [
        { t: 'Unique device fingerprint', d: 'IMEI, Android ID, MAC, model & serial — every instance is unique. Sidestep platform association checks.' },
        { t: 'Clean residential IP', d: '60+ countries of residential exit IPs, bound to a phone for as long as you need. 1:1 account-to-IP.' },
        { t: 'Native ARM compute', d: 'Android runs natively on ARM servers — no translation layer, performance near a real device.' },
        { t: '24/7 hosted', d: 'Always on. Offline grinders never disconnect. Scheduled wake, auto restart, all hands-off.' },
        { t: 'Team collaboration', d: 'Sub-accounts with role-based access, device groups, operation audit logs. Many hands, one matrix.' },
        { t: 'OpenAPI', d: 'RESTful API + webhooks. Drop Gloryphone into your RPA, automation scripts or in-house ops platform.' },
      ],
    },
    spotlight: {
      eyebrow: 'Control center',
      title: 'Visual mass control — a thousand phones, one console',
      sub: 'See hundreds of live device screens in your browser. One-click group control, templated tasks, cross-device sync.',
      bullets: [
        'Preview and control from any browser — no client install',
        'Screen mirror: one master device replays to N followers',
        'Record a script once, replay across a device group',
        'Auto-alerts on anomalies, auto-reconnect on drop',
      ],
      more: 'Learn more',
    },
    scenarios: {
      eyebrow: 'Use cases', title: "Whatever you run, we've run it",
      tabs: ['E-commerce', 'Social matrix', 'Game farms', 'Testing & dev', 'Mobile work'],
      panels: [
        { t: 'Multi-store on Amazon / Shopee / TikTok Shop', d: 'One dedicated device + dedicated IP per store, permanently bound. A single seller can run 50+ stores without association bans.',
          m: [['50+', 'Concurrent stores'], ['0', 'Association bans'], ['6', 'Global regions']] },
        { t: 'TikTok / Instagram / Twitter matrix', d: 'A dedicated environment per persona. Warm-up, posting and engagement all happen in the cloud. 3× higher account survival.',
          m: [['1000+', 'Accounts in matrix'], ['95%', 'Survival rate'], ['24h', 'Always online']] },
        { t: 'Game multi-boxing · long-run idle', d: 'Native ARM performance runs the latest mobile titles smoothly. Guild quests, dailies — 24/7 automated.',
          m: [['60 fps', 'Stable framerate'], ['24h', 'Idle uptime'], ['100+', 'Parallel boxes']] },
        { t: 'App testing · compatibility QA', d: 'Coverage across major models and Android versions. ADB direct in CI — overnight regression done by morning.',
          m: [['8-14', 'Android versions'], ['120+', 'Device models'], ['API', 'ADB / WDA']] },
        { t: 'BYOD · mobile work', d: "Employees don't install corporate apps locally. Sensitive data stays in the cloud — revoke access on day one.",
          m: [['0', 'Local data leak'], ['AES-256', 'Encrypted transit'], ['SSO', 'Enterprise directory']] },
      ],
    },
    compare: {
      eyebrow: 'Side by side', title: 'Why teams switch from emulators to Gloryphone',
      sub: 'Real hardware is expensive, emulators get flagged. Cloud phones are the answer.',
      cols: ['', 'Real hardware', 'PC emulator', 'Other cloud', 'Gloryphone'],
      rows: [
        ['Real hardware fingerprint', '✓', '✗', 'Partial', '✓'],
        ['Dedicated residential IP', 'BYO', 'BYO', 'Throttled', 'Native'],
        ['24/7 always-on', 'Charge it', 'Boot it', '✓', '✓'],
        ['Bulk management', 'Hard', 'Tedious', 'Some', 'Visual mass control'],
        ['Scale-up speed', 'Days', 'Hours', 'Hours', 'Seconds'],
        ['Per device / mo', '$30+', '$10+', '$18', 'From $9'],
      ],
    },
    perf: {
      eyebrow: 'Performance', title: 'Real hardware. Real numbers.',
      sub: 'Powered by our own ARM server nodes. CPU, GPU and memory are allocated per device — no oversubscription.',
      bars: [
        ['GeekBench single-core', 92], ['GeekBench multi-core', 88], ['3DMark Wildlife', 80],
        ['AnTuTu total', 87], ['Memory bandwidth', 95], ['I/O throughput', 91],
      ],
      stats: [
        ['8 cores', 'ARM v9 physical'], ['12 GB', 'Dedicated RAM'], ['1 Gbps', 'Outbound'], ['<30 ms', 'Global latency'],
      ],
    },
    pricing: {
      eyebrow: 'Pricing', title: 'Pay as you grow, save as you scale',
      sub: 'Pay from your wallet, provision in seconds. Buy more or longer for bigger discounts — every purchase and renewal gifts runtime minutes.',
      currency: '￥',
      badgeTrial: 'Free trial for new users', badgeGift: 'Seats gift runtime',
      ctaStart: 'Start free', ctaMore: 'Billing rules',
      fromLabel: 'As low as', unitMonth: 'mo', unitDay: 'day', unitMinute: 'min',
      perSeat: 'phone', perSlot: 'slot',
      resTitle: 'Three resources, mix as you need', resSub: 'Seats decide how many phones you can own, boot slots how many run at once, runtime minutes top it up by the minute.',
      seat: { name: 'Instance seat', desc: 'How many cloud phones you can own, billed monthly.', feats: ['1 seat = 1 cloud phone', 'Auto hot-migration on expiry', 'Renew one or many', 'Lower unit price at volume'] },
      boot: { name: 'Boot slot', desc: 'How many instances run concurrently, billed daily.', feats: ['Instances share slots in turns', 'Running on a slot costs no runtime', 'Buy by the day', 'Great for staggered ops'] },
      rt: { name: 'Runtime minutes', desc: 'Metered by the minute, never expires.', feats: ['Charged after a full minute', 'Daily per-phone cap', 'Buy anytime, no expiry', 'Falls back when slots are full'] },
      discEyebrow: 'Tiered discounts', discTitle: 'Buy more or longer, save more', discSub: 'Quantity tiers × duration discounts stack — priced live on the server.',
      discQtyHead: 'More units, lower price', discDurHead: 'Longer term, lower price', discPackHead: 'Bigger packs, lower price',
      giftEyebrow: 'Exclusive perk', giftTitle: 'Every instance seat gifts {min} runtime minutes per month',
      giftDesc: 'On new purchases and renewals alike. Gift = minutes per seat·month × seats × months — so a seat is never stuck unable to boot.',
      giftExample: 'e.g. renew 2 phones × 3 months and instantly get {total} runtime minutes',
      trialEyebrow: 'Try for free', trialTitle: 'Free trial for new users', trialSub: 'Claim on sign-up. Try the full product before you buy.', trialCta: 'Sign up to claim',
      subjSeat: 'Instance seats', subjBoot: 'Boot slots', subjRuntime: 'Runtime minutes',
      daysWord: 'days', minuteWord: 'min', permanentWord: 'never expires',
      teaserMore: 'See full pricing',
    },
    testi: {
      eyebrow: 'Customers', title: 'Chosen by 8,000+ teams worldwide',
      items: [
        { name: 'Daniel L.', role: 'TikTok Shop seller · US', text: 'Emulators kept tripping association checks. Three months on Gloryphone, zero stores banned.', initials: 'DL' },
        { name: 'Chen Q.', role: 'MCN ops director · Shenzhen', text: '600 IG accounts in a matrix. One click in the console updates the banner on every one of them. We saved half a team.', initials: 'CQ' },
        { name: 'Mariko T.', role: 'Mobile QA lead · Tokyo', text: 'We plugged Gloryphone into CI via the API. Regression runs overnight, reports waiting by morning.', initials: 'MT' },
        { name: 'Ahmad K.', role: 'Web3 community ops · Dubai', text: 'Discord and Twitter matrix finally without risk-control noise. The residential IPs are cleaner than any proxy we used.', initials: 'AK' },
        { name: 'Liu Z.', role: 'Game studio · Hangzhou', text: '150 phones idling AFK Arena monthly cards. Cost dropped from ¥15k to ¥4k — payback in 11 days.', initials: 'LZ' },
        { name: 'Sarah M.', role: 'Amazon top seller · London', text: 'Their CSM fixed an IP routing issue at 2am for me. You cannot find this kind of service in Europe.', initials: 'SM' },
      ],
    },
    download: {
      eyebrow: 'Apps', title: 'Anywhere, any device',
      sub: 'Web works out of the box. Desktop and mobile clients add a smoother experience.',
      items: [
        { name: 'Windows', ver: 'v3.8.2 · 64-bit', size: '128 MB' },
        { name: 'macOS', ver: 'v3.8.2 · Universal', size: '142 MB' },
        { name: 'Android', ver: 'v3.8.0 · APK', size: '48 MB' },
        { name: 'iOS', ver: 'v3.7.5 · TestFlight', size: 'App Store' },
      ],
      btn: 'Download',
    },
    blog: {
      eyebrow: 'Blog', title: 'Operations · Engineering · Trends',
      sub: 'Hands-on playbooks, product updates and cross-border insights from the Gloryphone team.',
      all: 'All posts', readMore: 'Read more', min: 'min read', updated: 'Updated',
      category: 'Category', tags: 'Tags',
      empty: 'No articles yet', error: "Couldn't load articles, please try again", retry: 'Retry',
      prev: 'Prev', next: 'Next',
    },
    docs: { updated: 'Last updated' },
    faq: {
      eyebrow: 'FAQ', title: 'Things you might want to ask',
      empty: 'No FAQs yet', error: "Couldn't load FAQs, please try again", retry: 'Retry', all: 'All',
    },
    feedback: {
      title: 'Was this article helpful?',
      helpful: 'Yes', notHelpful: 'No',
      thanksVote: 'Thanks for your feedback!',
      reportTitle: 'Found an issue or have a suggestion?',
      reportToggle: 'Leave feedback',
      placeholder: 'Describe the problem or your suggestion…',
      contact: 'Contact (optional, so we can follow up)',
      submit: 'Submit', submitting: 'Submitting…',
      thanksFeedback: 'Received — thank you for your feedback!',
      emptyError: 'Please enter your feedback first', error: 'Failed to submit, please try again',
    },
    cta: {
      title: 'Try it free. See what cloud phones can do for you.',
      sub: 'No credit card. Provision in seconds.',
      btn1: 'Start free trial', btn2: 'Book a demo',
    },
    footer: {
      desc: 'Cloud ARM compute and mobile automation infrastructure for global teams.',
      cols: [
        { title: 'Product', links: ['Cloud phones', 'Control Center', 'OpenAPI', 'Download', 'Changelog'] },
        { title: 'Solutions', links: ['E-commerce', 'Social matrix', 'Game farms', 'App testing', 'Mobile work'] },
        { title: 'Resources', links: ['Help center', 'API docs', 'Status', 'Blog', 'News'] },
        { title: 'Company', links: ['About', 'Careers', 'Contact sales', 'Terms', 'Privacy'] },
      ],
      aiDocs: 'AI Docs',
      copy: '© 2026 Gloryphone Tech. All rights reserved.',
      beian: 'Reg. 2026000000',
    },
    cookies: {
      banner: {
        title: 'We value your privacy',
        body: 'We use cookies to keep the site running and, with your consent, for analytics and personalized marketing.',
        accept: 'Accept all',
        reject: 'Necessary only',
        customize: 'Customize',
        manage: 'Manage preferences',
        learnMore: 'Learn more',
      },
      prefs: {
        title: 'Cookie preferences',
        save: 'Save preferences',
        acceptAll: 'Accept all',
        rejectAll: 'Reject all',
        savedAt: 'Last updated: {time}',
        notDecided: 'No choice made yet',
        alwaysOn: 'Always on',
      },
      categories: {
        necessary: { name: 'Necessary', desc: 'Required for login, security and core features. Cannot be disabled.' },
        functional: { name: 'Functional', desc: 'Remember preferences like language and theme to improve your experience.' },
        analytics: { name: 'Analytics', desc: 'Anonymous usage statistics that help us improve the product.' },
        marketing: { name: 'Marketing', desc: 'Used to measure ad performance and personalize cross-site promotions.' },
      },
      policy: {
        title: 'Cookie Policy',
        updated: 'Last updated: June 2026',
        intro: 'This policy explains how we use cookies and similar technologies, and how you can manage your preferences.',
        sections: [
          { h: 'What are cookies', p: 'Cookies are small text files a site stores on your device to remember your actions and preferences.' },
          { h: 'How we use them', p: 'To keep the site working, remember preferences, measure usage, and — with consent — personalize marketing.' },
          { h: 'Third parties & transfers', p: 'Some analytics and ad cookies are set by third parties; data may be processed outside your region.' },
          { h: 'Withdrawing consent', p: 'You can change preferences anytime here or clear browser cookies; withdrawal does not affect prior lawful processing.' },
          { h: 'Contact us', p: 'For privacy questions, reach us via the contact details in the footer.' },
        ],
      },
    },
    theme: { color: 'Accent', dark: 'Dark', light: 'Light', system: 'System', language: 'Language', appearance: 'Appearance', accent: 'Accent', mode: 'Mode' },
  },
} as const

export type GpContent = (typeof GP_CONTENT)['en']

/**
 * Returns the full content object for the active locale, plus the raw locale.
 * Mirrors the reference design's `useApp().t`.
 */
export function useGp() {
  const { locale } = useI18n()
  const t = computed<GpContent>(() => (GP_CONTENT as any)[locale.value] ?? GP_CONTENT.en)
  return { t, locale }
}
