// Full content dictionary, ported verbatim from the high-fidelity reference
// design (ref/sytle12-claude-design/index.html). Keyed by Nuxt i18n locale
// codes ('zh' | 'en'). Structured arrays/objects are read directly from here
// instead of through vue-i18n message functions.

export const GP_CONTENT = {
  zh: {
    locale: '简体中文',
    promo: {
      tag: '2026 年中大促',
      title: '充 $50 起享赠送',
      body: '充 $100 得 $120，充 $1000 得 $1300，最高赠 30%',
      cta: '立即领取',
      countdown: '活动至 6.30 (UTC+0)',
    },
    nav: {
      home: '首页', product: '产品', features: '功能特性', scenarios: '应用场景',
      pricing: '价格套餐', specs: '性能规格', customers: '客户案例',
      download: '下载', blog: '博客', help: '帮助中心', news: '新闻动态',
      login: '登录', signup: '免费注册', trial: '免费试用',
      console: '控制台', logout: '退出登录', account: '账户',
    },
    hero: {
      tag: '海外营销 · 跨境电商 · 多账号矩阵',
      title1: '一人千号', titleHL: '云端运营', title2: '如同本地',
      sub: '为海外社媒、跨境电商团队打造的云手机平台。独立 IP、独立设备指纹、24 小时在线，让你的 TikTok、WhatsApp、Shopee 矩阵稳定运转。',
      cta1: '免费试用 1 小时', cta2: '查看演示',
      trust1: '全球 22 个节点', trust2: '原生 ARM 性能', trust3: '金融级数据隔离',
    },
    stats: {
      devices: '在线云手机', devicesL: '全球同时在线',
      users: '企业客户', usersL: '覆盖 60+ 国家',
      uptime: '服务可用性', uptimeL: 'SLA 99.99%',
      ips: '独立出口 IP', ipsL: '可分配纯净 IP 池',
    },
    logos: '受信于全球团队',
    features: {
      eyebrow: '为何选择 Gloryphone',
      title: '一台手机做不到的，云手机一次给你',
      sub: '原生 Android 系统，云端集群运行。每一台都是真实硬件指纹、真实设备 ID、独立网络环境。',
      items: [
        { t: '独立设备指纹', d: 'IMEI、Android ID、MAC、机型、序列号每台独一无二，规避平台关联检测。' },
        { t: '纯净住宅 IP', d: '支持 60+ 国家住宅级出口 IP，可绑定到指定云手机长期使用，IP 与账号 1:1。' },
        { t: 'ARM 原生算力', d: '基于 ARM 服务器原生运行 Android，无需翻译层，性能逼近真机。' },
        { t: '24 小时托管', d: '云端常驻，离线挂机不掉号；自动任务、定时唤醒、关机重启全自动。' },
        { t: '团队协作', d: '子账号权限、设备分组、操作日志审计，支持多人同时管理同一矩阵。' },
        { t: 'OpenAPI 集成', d: 'RESTful API + Webhook，对接 RPA、自动化脚本、自有运营平台。' },
      ],
    },
    spotlight: {
      eyebrow: '云控台',
      title: '可视化批量操控，千台如同一台',
      sub: '在浏览器里同时看到上百台设备的实时画面。一键群控、模板化任务、跨设备同步操作。',
      bullets: [
        '网页直接预览与控制，无需安装客户端',
        '屏幕复制：1 台主控同步到 N 台从机',
        '脚本录制 → 一键回放到指定分组',
        '异常自动告警，掉线自动重连',
      ],
      more: '了解更多',
    },
    scenarios: {
      eyebrow: '应用场景', title: '你的业务，我们都跑过',
      tabs: ['跨境电商', '社媒矩阵', '游戏挂机', '测试与开发', '企业办公'],
      panels: [
        { t: '亚马逊 / Shopee / TikTok Shop 多店铺', d: '每店铺一个独立设备 + 独立 IP，永久绑定。卖家可以一人同时管理 50+ 店铺，不再担心账号关联封号。',
          m: [['50+', '并发店铺'], ['0', '关联封号'], ['6', '全球区域']] },
        { t: 'TikTok / Instagram / Twitter 矩阵', d: '为每个 IP 形象建立专属环境，养号、发布、互动全流程在云端完成。账号留存率提升 3 倍。',
          m: [['1000+', '矩阵账号'], ['95%', '存活率'], ['24h', '云端在线']] },
        { t: '游戏多开 · 长线挂机', d: '原生 ARM 性能，主流手游流畅运行；公会任务、日常副本自动化，账号 24 小时不掉线。',
          m: [['60', 'FPS 稳定'], ['24h', '挂机不掉'], ['100+', '并发开图']] },
        { t: '应用测试 · 兼容性验证', d: '覆盖主流机型与 Android 版本，CI 集成 ADB 直连，回归自动化测试一晚跑完。',
          m: [['8-14', 'Android 版本'], ['120+', '机型库'], ['API', 'ADB / WDA']] },
        { t: 'BYOD · 移动办公', d: '员工自有设备无需安装企业 App，敏感数据 100% 留在云端，离职即收回访问权。',
          m: [['0', '数据落本地'], ['AES-256', '通信加密'], ['SSO', '企业目录']] },
      ],
    },
    compare: {
      eyebrow: '横向对比', title: '为什么团队从模拟器换到 Gloryphone',
      sub: '本地真机贵、模拟器假，云手机才是给团队的最优解。',
      cols: ['', '本地真机', 'PC 模拟器', '其他云服务', 'Gloryphone'],
      rows: [
        ['真实硬件指纹', '✓', '✗', '部分', '✓'],
        ['独立住宅 IP', '需自购', '需自购', '限速', '原生支持'],
        ['24 小时常驻', '需充电', '需开机', '✓', '✓'],
        ['批量管理', '极难', '麻烦', '支持', '可视化群控'],
        ['扩容速度', '天级', '小时级', '小时级', '秒级'],
        ['单台月成本', '￥30+', '￥10+', '￥18', '￥9 起'],
      ],
    },
    perf: {
      eyebrow: '性能', title: '真硬件，真性能',
      sub: '搭载自研 ARM 服务器节点，CPU、GPU、内存按设备隔离分配，无超售。',
      bars: [
        ['GeekBench 单核', 92], ['GeekBench 多核', 88], ['3DMark Wildlife', 80],
        ['AnTuTu 综合', 87], ['内存带宽', 95], ['I/O 读写', 91],
      ],
      stats: [
        ['8 核', 'ARM v9 物理核心'], ['12 GB', '独立内存'], ['1 Gbps', '出口带宽'], ['<30 ms', '全球延迟'],
      ],
    },
    pricing: {
      eyebrow: '价格', title: '按台计费，按需付费',
      sub: '无最低消费，分钟级开通，随时升降配。',
      monthly: '按月', yearly: '按年', save: '省 20%', currency: '￥',
      plans: [
        { name: '试用版', desc: '适合个人初次体验', price: 0, per: '/小时', features: ['1 台云手机', '共享 IP', '1080p 画质', '在线客服'], cta: '免费开通' },
        { name: '标准版', desc: '适合个人卖家、自由职业者', price: 9, per: '/台/月', features: ['独立设备指纹', '30+ 国家住宅 IP', '1080p · 60fps', 'API 接入', '邮件支持'], cta: '立即购买' },
        { name: '团队版', desc: '适合 5-50 人电商/社媒团队', price: 29, per: '/台/月', features: ['标准版全部能力', '可视化群控台', '子账号 + 权限组', '操作日志审计', '7×24 人工支持'], cta: '立即购买', featured: true, tag: '最受欢迎' },
        { name: '企业版', desc: '适合 100+ 设备、私有部署', price: '定制', per: '', features: ['专属物理节点', '私有 IP 池', 'SLA 99.99%', '专属客户经理', '可私有化部署'], cta: '联系销售' },
      ],
    },
    testi: {
      eyebrow: '客户怎么说', title: '全球 8,000+ 团队的选择',
      items: [
        { name: 'Daniel L.', role: 'TikTok Shop 卖家 · 美国', text: '之前用模拟器频繁触发关联检测，换到 Gloryphone 之后 3 个月没有一个店铺被封。', initials: 'DL' },
        { name: '陈茜', role: 'MCN 运营总监 · 深圳', text: '矩阵 600 个 IG 账号，群控台一次点击全部更新主页 banner，省下了半个团队的人力。', initials: '陈' },
        { name: 'Mariko T.', role: 'Mobile QA Lead · 东京', text: '我们用 API 把 Gloryphone 接进了 CI/CD，凌晨自动跑回归，早上看报告，效率翻倍。', initials: 'MT' },
        { name: 'Ahmad K.', role: 'Web3 社区运营 · 迪拜', text: 'Discord & Twitter 矩阵管理终于不再被风控。住宅 IP 质量比我之前买的任何代理都干净。', initials: 'AK' },
        { name: '刘振', role: '游戏工作室 · 杭州', text: '150 台云手机挂《剑与远征》月卡号，月成本从 1.5w 降到 4k，回本周期 11 天。', initials: '刘' },
        { name: 'Sarah M.', role: '亚马逊大卖 · 伦敦', text: '客户经理半夜帮我解决 IP 切换问题，这种服务在欧洲根本找不到。', initials: 'SM' },
      ],
    },
    download: {
      eyebrow: '客户端', title: '随时随地，多端同步',
      sub: '网页端开箱即用；桌面 / 移动客户端提供更流畅的体验。',
      items: [
        { name: 'Windows', ver: 'v3.8.2 · 64-bit', size: '128 MB' },
        { name: 'macOS', ver: 'v3.8.2 · Universal', size: '142 MB' },
        { name: 'Android', ver: 'v3.8.0 · APK', size: '48 MB' },
        { name: 'iOS', ver: 'v3.7.5 · TestFlight', size: 'App Store' },
      ],
      btn: '立即下载',
    },
    blog: {
      eyebrow: '博客', title: '运营 · 技术 · 趋势',
      sub: '来自 Gloryphone 团队的实战经验、产品更新与跨境营销洞察。',
      all: '查看全部', readMore: '阅读全文', min: '分钟阅读',
      posts: [
        { id: 'tiktok-shop-compliance-2026', cover: 11, cat: '跨境电商', date: '2026-05-22', read: 8,
          title: 'TikTok Shop 多店铺 2026 合规指南：账号关联是怎么发生的',
          excerpt: '深度拆解平台的设备关联检测逻辑，给出云手机环境下的最佳隔离实践，附完整 checklist。' },
        { id: 'control-center-v3-recipe', cover: 22, cat: '产品更新', date: '2026-05-08', read: 5,
          title: '群控台 V3：录制一段操作，回放到 1000 台设备',
          excerpt: '新版脚本录制器把繁琐的批量任务压缩到一次点击。带你从 0 到 1 跑通一个真实工作流。' },
        { id: 'residential-ip-quality', cover: 35, cat: '技术深度', date: '2026-04-19', read: 11,
          title: '什么样的住宅 IP 才算干净？我们扫了 12 家供应商',
          excerpt: '对比 12 家市售住宅代理在 6 个主流平台上的存活率、解封比例与价格档位，给出选型矩阵。' },
        { id: 'matrix-account-survival', cover: 48, cat: '运营技巧', date: '2026-04-02', read: 7,
          title: '1000+ 社媒账号矩阵的存活率打法',
          excerpt: '从设备指纹到内容差异化，6 条经过验证的提升账号存活率的标准动作。' },
        { id: 'openapi-v2-webhook', cover: 56, cat: '开发者', date: '2026-03-15', read: 6,
          title: 'OpenAPI v2 上手：用 Webhook 把云手机接入你的 RPA',
          excerpt: '事件驱动的设备控制范式 — 用 50 行 Python 串起 Gloryphone + n8n + Telegram 告警。' },
        { id: 'byod-zero-data-on-device', cover: 67, cat: '企业IT', date: '2026-03-01', read: 9,
          title: 'BYOD 真的可以做到 0 数据落本地吗？',
          excerpt: '一次实测：员工自有 Android 手机访问敏感系统，会留下哪些痕迹？怎么真正清零？' },
        { id: 'android-arm-native-perf', cover: 73, cat: '技术深度', date: '2026-02-12', read: 10,
          title: 'ARM 服务器原生跑 Android 与 x86 翻译层的性能差距',
          excerpt: '三款主流手游 + GeekBench 实测，量化原生与转译的性能与功耗代价。' },
        { id: 'tiktok-live-from-cloud', cover: 81, cat: '运营技巧', date: '2026-01-28', read: 6,
          title: '用云手机做 TikTok 直播，平台会识别吗？',
          excerpt: '把云手机推流接到 TikTok 直播，从设备识别到画面延迟的完整对比测试。' },
        { id: 'ci-cd-android-farm', cover: 94, cat: '开发者', date: '2026-01-14', read: 8,
          title: '把云手机接进 GitHub Actions：5 分钟跑完 50 机型回归',
          excerpt: 'ADB-over-WebSocket + 矩阵任务，把过去一晚上的回归压到一次 CI 内完成。' },
      ],
    },
    faq: {
      eyebrow: '常见问题', title: '你可能想问',
      items: [
        ['云手机和模拟器有什么区别？', '云手机是运行在云端 ARM 服务器上的真实 Android 系统，拥有真实的硬件指纹和独立网络环境；模拟器是 PC 上的虚拟运行环境，平台风控很容易识别。'],
        ['IP 是干净的吗？会不会被标记？', '我们提供原生住宅级出口 IP，每一个都来自真实家庭宽带运营商，IP 池每日动态补充并做风控筛查。'],
        ['可以绑定我自己的 IP 或代理吗？', '可以。在控制台为云手机配置自定义 SOCKS5 / HTTP 代理，或通过 API 批量绑定，支持账号-IP-设备永久 1:1。'],
        ['数据安全如何保证？', '所有传输 TLS 1.3 加密，云端存储 AES-256；企业版可使用专属物理节点，数据不与其他用户共享。'],
        ['可以退款吗？', '标准版与团队版支持 7 天无理由退款；按月购买不满意可随时停用，按实际使用时长计费。'],
        ['有 API 吗？支持自动化？', '提供完整的 RESTful API 与 Webhook，支持设备开机/关机、IP 切换、应用安装、ADB 直连、文件上传等所有操作。'],
      ],
    },
    cta: {
      title: '1 小时免费试用，看看云手机能为你做什么',
      sub: '无需信用卡，注册即用。',
      btn1: '立即免费试用', btn2: '预约演示',
    },
    footer: {
      desc: '为全球团队提供云端 ARM 算力与移动自动化基础设施。',
      cols: [
        { title: '产品', links: ['云手机', '群控台', 'OpenAPI', '客户端下载', '更新日志'] },
        { title: '解决方案', links: ['跨境电商', '社媒矩阵', '游戏挂机', '应用测试', '企业办公'] },
        { title: '资源', links: ['帮助中心', '开发者文档', '状态页', '博客', '新闻动态'] },
        { title: '公司', links: ['关于我们', '加入我们', '联系销售', '服务协议', '隐私政策'] },
      ],
      copy: '© 2026 Gloryphone Tech.  保留所有权利。',
      beian: '粤 ICP 备 2026000000 号-1',
    },
    cookies: {
      banner: {
        title: '我们重视你的隐私',
        body: '我们使用 Cookie 保障网站正常运行，并在你同意后用于分析与个性化营销。',
        accept: '全部接受',
        reject: '仅必要',
        customize: '自定义',
        manage: '管理偏好',
        learnMore: '了解更多',
      },
      prefs: {
        title: 'Cookie 偏好',
        save: '保存偏好',
        acceptAll: '全部接受',
        rejectAll: '全部拒绝',
        savedAt: '上次更新：{time}',
        notDecided: '尚未做出选择',
        alwaysOn: '始终启用',
      },
      categories: {
        necessary: { name: '必要', desc: '保障登录、安全与基本功能，无法关闭。' },
        functional: { name: '功能性', desc: '记住语言、主题等偏好，提升使用体验。' },
        analytics: { name: '分析', desc: '匿名统计访问数据，帮助我们改进产品。' },
        marketing: { name: '广告', desc: '用于衡量广告效果与跨站个性化推广。' },
      },
      policy: {
        title: 'Cookie 政策',
        updated: '最近更新：2026 年 6 月',
        intro: '本政策说明我们如何使用 Cookie 及类似技术，以及你如何管理偏好。',
        sections: [
          { h: '什么是 Cookie', p: 'Cookie 是网站存放在你设备上的小型文本文件，用于记住你的操作与偏好。' },
          { h: '我们的使用目的', p: '保障网站运行、记住偏好、统计分析，并在你同意后用于个性化营销。' },
          { h: '第三方与跨境', p: '部分分析与广告 Cookie 由第三方提供，数据可能在你所在地区之外处理。' },
          { h: '如何撤回同意', p: '你可随时在本页修改偏好，或清除浏览器 Cookie；撤回不影响此前处理的合法性。' },
          { h: '联系我们', p: '如对隐私有疑问，可通过页脚的联系方式与我们取得联系。' },
        ],
      },
    },
    theme: { color: '主题色', dark: '深色模式', light: '浅色模式', system: '跟随系统', language: '语言', appearance: '外观调节', accent: '配色', mode: '明暗' },
  },

  en: {
    locale: 'English',
    promo: {
      tag: '2026 Mid-Year Sale',
      title: 'Top up from $50',
      body: 'Recharge $100 get $120 · Recharge $1000 get $1300 · Up to +30%',
      cta: 'Claim now',
      countdown: 'Ends 6.30 (UTC+0)',
    },
    nav: {
      home: 'Home', product: 'Product', features: 'Features', scenarios: 'Use cases',
      pricing: 'Pricing', specs: 'Performance', customers: 'Customers',
      download: 'Download', blog: 'Blog', help: 'Help', news: 'News',
      login: 'Sign in', signup: 'Sign up free', trial: 'Free trial',
      console: 'Console', logout: 'Sign out', account: 'Account',
    },
    hero: {
      tag: 'Overseas marketing · Cross-border e-commerce · Multi-account',
      title1: 'Run a thousand phones,', titleHL: 'from one browser tab', title2: '',
      sub: 'A cloud phone platform built for overseas social and e-commerce teams. Dedicated IP, unique device fingerprint, 24/7 online — keep your TikTok, WhatsApp and Shopee matrix running smoothly.',
      cta1: 'Try free for 1 hour', cta2: 'Watch demo',
      trust1: '22 global regions', trust2: 'Native ARM silicon', trust3: 'Bank-grade isolation',
    },
    stats: {
      devices: 'Online phones', devicesL: 'Concurrent worldwide',
      users: 'Business customers', usersL: 'Across 60+ countries',
      uptime: 'Service uptime', uptimeL: '99.99% SLA',
      ips: 'Dedicated IPs', ipsL: 'Clean residential pool',
    },
    logos: 'Trusted by teams worldwide',
    features: {
      eyebrow: 'Why Gloryphone',
      title: "Everything one phone can't do — solved.",
      sub: 'Native Android running on cloud ARM clusters. Each instance has its own hardware fingerprint, device ID and network.',
      items: [
        { t: 'Unique device fingerprint', d: 'IMEI, Android ID, MAC, model & serial — every instance is unique. Sidestep platform association checks.' },
        { t: 'Clean residential IP', d: '60+ countries of residential exit IPs, bound to a phone for as long as you need. 1:1 account-to-IP.' },
        { t: 'Native ARM compute', d: 'Android runs natively on ARM servers — no translation layer, performance near a real device.' },
        { t: '24/7 hosted', d: 'Always on. Offline grinders never disconnect. Scheduled wake, auto restart, all hands-off.' },
        { t: 'Team collaboration', d: 'Sub-accounts with role-based access, device groups, operation audit logs. Many hands, one matrix.' },
        { t: 'OpenAPI', d: 'RESTful API + webhooks. Drop Gloryphone into your RPA, automation scripts or in-house ops platform.' },
      ],
    },
    spotlight: {
      eyebrow: 'Control center',
      title: 'Visual mass control — a thousand phones, one console',
      sub: 'See hundreds of live device screens in your browser. One-click group control, templated tasks, cross-device sync.',
      bullets: [
        'Preview and control from any browser — no client install',
        'Screen mirror: one master device replays to N followers',
        'Record a script once, replay across a device group',
        'Auto-alerts on anomalies, auto-reconnect on drop',
      ],
      more: 'Learn more',
    },
    scenarios: {
      eyebrow: 'Use cases', title: "Whatever you run, we've run it",
      tabs: ['E-commerce', 'Social matrix', 'Game farms', 'Testing & dev', 'Mobile work'],
      panels: [
        { t: 'Multi-store on Amazon / Shopee / TikTok Shop', d: 'One dedicated device + dedicated IP per store, permanently bound. A single seller can run 50+ stores without association bans.',
          m: [['50+', 'Concurrent stores'], ['0', 'Association bans'], ['6', 'Global regions']] },
        { t: 'TikTok / Instagram / Twitter matrix', d: 'A dedicated environment per persona. Warm-up, posting and engagement all happen in the cloud. 3× higher account survival.',
          m: [['1000+', 'Accounts in matrix'], ['95%', 'Survival rate'], ['24h', 'Always online']] },
        { t: 'Game multi-boxing · long-run idle', d: 'Native ARM performance runs the latest mobile titles smoothly. Guild quests, dailies — 24/7 automated.',
          m: [['60 fps', 'Stable framerate'], ['24h', 'Idle uptime'], ['100+', 'Parallel boxes']] },
        { t: 'App testing · compatibility QA', d: 'Coverage across major models and Android versions. ADB direct in CI — overnight regression done by morning.',
          m: [['8-14', 'Android versions'], ['120+', 'Device models'], ['API', 'ADB / WDA']] },
        { t: 'BYOD · mobile work', d: "Employees don't install corporate apps locally. Sensitive data stays in the cloud — revoke access on day one.",
          m: [['0', 'Local data leak'], ['AES-256', 'Encrypted transit'], ['SSO', 'Enterprise directory']] },
      ],
    },
    compare: {
      eyebrow: 'Side by side', title: 'Why teams switch from emulators to Gloryphone',
      sub: 'Real hardware is expensive, emulators get flagged. Cloud phones are the answer.',
      cols: ['', 'Real hardware', 'PC emulator', 'Other cloud', 'Gloryphone'],
      rows: [
        ['Real hardware fingerprint', '✓', '✗', 'Partial', '✓'],
        ['Dedicated residential IP', 'BYO', 'BYO', 'Throttled', 'Native'],
        ['24/7 always-on', 'Charge it', 'Boot it', '✓', '✓'],
        ['Bulk management', 'Hard', 'Tedious', 'Some', 'Visual mass control'],
        ['Scale-up speed', 'Days', 'Hours', 'Hours', 'Seconds'],
        ['Per device / mo', '$30+', '$10+', '$18', 'From $9'],
      ],
    },
    perf: {
      eyebrow: 'Performance', title: 'Real hardware. Real numbers.',
      sub: 'Powered by our own ARM server nodes. CPU, GPU and memory are allocated per device — no oversubscription.',
      bars: [
        ['GeekBench single-core', 92], ['GeekBench multi-core', 88], ['3DMark Wildlife', 80],
        ['AnTuTu total', 87], ['Memory bandwidth', 95], ['I/O throughput', 91],
      ],
      stats: [
        ['8 cores', 'ARM v9 physical'], ['12 GB', 'Dedicated RAM'], ['1 Gbps', 'Outbound'], ['<30 ms', 'Global latency'],
      ],
    },
    pricing: {
      eyebrow: 'Pricing', title: 'Per device, pay as you grow',
      sub: 'No minimum spend. Provision in seconds. Scale up or down anytime.',
      monthly: 'Monthly', yearly: 'Yearly', save: 'Save 20%', currency: '$',
      plans: [
        { name: 'Trial', desc: 'Try it before you commit', price: 0, per: '/hour', features: ['1 phone', 'Shared IP', '1080p', 'Live chat'], cta: 'Start free' },
        { name: 'Standard', desc: 'For solo sellers & freelancers', price: 9, per: '/phone/mo', features: ['Unique fingerprint', '30+ country residential IP', '1080p · 60fps', 'API access', 'Email support'], cta: 'Buy now' },
        { name: 'Team', desc: 'For 5–50 person e-com / social teams', price: 29, per: '/phone/mo', features: ['Everything in Standard', 'Visual mass control', 'Sub-accounts + roles', 'Audit logs', '24/7 human support'], cta: 'Buy now', featured: true, tag: 'Most popular' },
        { name: 'Enterprise', desc: '100+ devices, private deploy', price: 'Custom', per: '', features: ['Dedicated bare metal', 'Private IP pool', '99.99% SLA', 'Account manager', 'Private deployment'], cta: 'Contact sales' },
      ],
    },
    testi: {
      eyebrow: 'Customers', title: 'Chosen by 8,000+ teams worldwide',
      items: [
        { name: 'Daniel L.', role: 'TikTok Shop seller · US', text: 'Emulators kept tripping association checks. Three months on Gloryphone, zero stores banned.', initials: 'DL' },
        { name: 'Chen Q.', role: 'MCN ops director · Shenzhen', text: '600 IG accounts in a matrix. One click in the console updates the banner on every one of them. We saved half a team.', initials: 'CQ' },
        { name: 'Mariko T.', role: 'Mobile QA lead · Tokyo', text: 'We plugged Gloryphone into CI via the API. Regression runs overnight, reports waiting by morning.', initials: 'MT' },
        { name: 'Ahmad K.', role: 'Web3 community ops · Dubai', text: 'Discord and Twitter matrix finally without risk-control noise. The residential IPs are cleaner than any proxy we used.', initials: 'AK' },
        { name: 'Liu Z.', role: 'Game studio · Hangzhou', text: '150 phones idling AFK Arena monthly cards. Cost dropped from ¥15k to ¥4k — payback in 11 days.', initials: 'LZ' },
        { name: 'Sarah M.', role: 'Amazon top seller · London', text: 'Their CSM fixed an IP routing issue at 2am for me. You cannot find this kind of service in Europe.', initials: 'SM' },
      ],
    },
    download: {
      eyebrow: 'Apps', title: 'Anywhere, any device',
      sub: 'Web works out of the box. Desktop and mobile clients add a smoother experience.',
      items: [
        { name: 'Windows', ver: 'v3.8.2 · 64-bit', size: '128 MB' },
        { name: 'macOS', ver: 'v3.8.2 · Universal', size: '142 MB' },
        { name: 'Android', ver: 'v3.8.0 · APK', size: '48 MB' },
        { name: 'iOS', ver: 'v3.7.5 · TestFlight', size: 'App Store' },
      ],
      btn: 'Download',
    },
    blog: {
      eyebrow: 'Blog', title: 'Operations · Engineering · Trends',
      sub: 'Hands-on playbooks, product updates and cross-border insights from the Gloryphone team.',
      all: 'All posts', readMore: 'Read more', min: 'min read',
      posts: [
        { id: 'tiktok-shop-compliance-2026', cover: 11, cat: 'Commerce', date: '2026-05-22', read: 8,
          title: 'TikTok Shop multi-store compliance in 2026 — how account-linking really happens',
          excerpt: "We dissect the platform's device association logic and lay out an isolation playbook for cloud-phone environments. Includes a full checklist." },
        { id: 'control-center-v3-recipe', cover: 22, cat: 'Product', date: '2026-05-08', read: 5,
          title: 'Control Center V3: record once, replay across 1000 devices',
          excerpt: 'The new recorder compresses tedious bulk ops into a single click. Walking through a real end-to-end workflow.' },
        { id: 'residential-ip-quality', cover: 35, cat: 'Engineering', date: '2026-04-19', read: 11,
          title: "What does a 'clean' residential IP look like? We tested 12 vendors",
          excerpt: 'Survival rate, unblock ratio, and per-IP cost across 12 residential-proxy providers on 6 major platforms — with a vendor matrix.' },
        { id: 'matrix-account-survival', cover: 48, cat: 'Operations', date: '2026-04-02', read: 7,
          title: 'Survival tactics for a 1000+ social-media account matrix',
          excerpt: 'From device fingerprint to content variance — six proven moves that consistently lift account survival.' },
        { id: 'openapi-v2-webhook', cover: 56, cat: 'Developers', date: '2026-03-15', read: 6,
          title: 'OpenAPI v2 quickstart — wiring cloud phones into your RPA via webhooks',
          excerpt: 'Event-driven device control. 50 lines of Python tying Gloryphone, n8n, and Telegram alerts together.' },
        { id: 'byod-zero-data-on-device', cover: 67, cat: 'Enterprise IT', date: '2026-03-01', read: 9,
          title: 'Can BYOD truly leave zero data on-device?',
          excerpt: 'A field test: when an employee accesses sensitive systems from their own Android, what traces are left? How do you truly wipe them?' },
        { id: 'android-arm-native-perf', cover: 73, cat: 'Engineering', date: '2026-02-12', read: 10,
          title: 'ARM-native Android vs x86 translation: the real perf gap',
          excerpt: 'Three popular mobile games + GeekBench, quantified — the performance and power cost of native vs translated.' },
        { id: 'tiktok-live-from-cloud', cover: 81, cat: 'Operations', date: '2026-01-28', read: 6,
          title: 'Going live on TikTok from a cloud phone — will the platform notice?',
          excerpt: 'End-to-end comparison from device fingerprint to stream latency, streaming a cloud phone to TikTok Live.' },
        { id: 'ci-cd-android-farm', cover: 94, cat: 'Developers', date: '2026-01-14', read: 8,
          title: 'Plug a cloud-phone farm into GitHub Actions: 50-device regression in 5 minutes',
          excerpt: 'ADB-over-WebSocket + matrix jobs, an overnight regression squeezed into one CI run.' },
      ],
    },
    faq: {
      eyebrow: 'FAQ', title: 'Things you might want to ask',
      items: [
        ["What's the difference between a cloud phone and an emulator?", 'A cloud phone is a real Android instance on an ARM server in the cloud — with real hardware fingerprint and a dedicated network. An emulator is a virtual environment on your PC and is trivially detectable by platform risk controls.'],
        ['Are the IPs clean? Will they get flagged?', 'Yes. We provide native residential exit IPs from real consumer ISPs. The pool is refreshed daily and risk-scored before allocation.'],
        ['Can I bring my own IP or proxy?', 'You can. Configure a custom SOCKS5 / HTTP proxy per device in the console, or batch-bind via API. Account-IP-device 1:1 can be made permanent.'],
        ['How is my data secured?', 'Everything in flight is TLS 1.3, everything at rest is AES-256. Enterprise plans get a dedicated bare-metal node — your data never shares a host with anyone else.'],
        ['Refund policy?', 'Standard and Team plans get a 7-day no-questions-asked refund. Monthly subscribers can stop any time — we bill by actual usage.'],
        ['Is there an API for automation?', 'Yes — full REST + webhooks. Boot, shut down, switch IP, install app, ADB tunnel, file upload, screenshot — all scriptable.'],
      ],
    },
    cta: {
      title: 'Try it free for an hour. See what cloud phones can do for you.',
      sub: 'No credit card. Provision in seconds.',
      btn1: 'Start free trial', btn2: 'Book a demo',
    },
    footer: {
      desc: 'Cloud ARM compute and mobile automation infrastructure for global teams.',
      cols: [
        { title: 'Product', links: ['Cloud phones', 'Control Center', 'OpenAPI', 'Download', 'Changelog'] },
        { title: 'Solutions', links: ['E-commerce', 'Social matrix', 'Game farms', 'App testing', 'Mobile work'] },
        { title: 'Resources', links: ['Help center', 'API docs', 'Status', 'Blog', 'News'] },
        { title: 'Company', links: ['About', 'Careers', 'Contact sales', 'Terms', 'Privacy'] },
      ],
      copy: '© 2026 Gloryphone Tech. All rights reserved.',
      beian: 'Reg. 2026000000',
    },
    cookies: {
      banner: {
        title: 'We value your privacy',
        body: 'We use cookies to keep the site running and, with your consent, for analytics and personalized marketing.',
        accept: 'Accept all',
        reject: 'Necessary only',
        customize: 'Customize',
        manage: 'Manage preferences',
        learnMore: 'Learn more',
      },
      prefs: {
        title: 'Cookie preferences',
        save: 'Save preferences',
        acceptAll: 'Accept all',
        rejectAll: 'Reject all',
        savedAt: 'Last updated: {time}',
        notDecided: 'No choice made yet',
        alwaysOn: 'Always on',
      },
      categories: {
        necessary: { name: 'Necessary', desc: 'Required for login, security and core features. Cannot be disabled.' },
        functional: { name: 'Functional', desc: 'Remember preferences like language and theme to improve your experience.' },
        analytics: { name: 'Analytics', desc: 'Anonymous usage statistics that help us improve the product.' },
        marketing: { name: 'Marketing', desc: 'Used to measure ad performance and personalize cross-site promotions.' },
      },
      policy: {
        title: 'Cookie Policy',
        updated: 'Last updated: June 2026',
        intro: 'This policy explains how we use cookies and similar technologies, and how you can manage your preferences.',
        sections: [
          { h: 'What are cookies', p: 'Cookies are small text files a site stores on your device to remember your actions and preferences.' },
          { h: 'How we use them', p: 'To keep the site working, remember preferences, measure usage, and — with consent — personalize marketing.' },
          { h: 'Third parties & transfers', p: 'Some analytics and ad cookies are set by third parties; data may be processed outside your region.' },
          { h: 'Withdrawing consent', p: 'You can change preferences anytime here or clear browser cookies; withdrawal does not affect prior lawful processing.' },
          { h: 'Contact us', p: 'For privacy questions, reach us via the contact details in the footer.' },
        ],
      },
    },
    theme: { color: 'Accent', dark: 'Dark', light: 'Light', system: 'System', language: 'Language', appearance: 'Appearance', accent: 'Accent', mode: 'Mode' },
  },
} as const

// ---------------------------------------------------------------------------
// Article bodies, keyed by post id then locale. Each body is an ordered list of
// blocks: { k: 'p' | 'h2' | 'ul', t?: string, items?: string[] }.
// ---------------------------------------------------------------------------
export interface ArticleBlock {
  k: 'p' | 'h2' | 'ul'
  t?: string
  items?: string[]
}

export const GP_ARTICLE_BODIES: Record<'zh' | 'en', Record<string, ArticleBlock[]>> = {
  zh: {
    'tiktok-shop-compliance-2026': [
      { k: 'p', t: 'TikTok Shop 的多店铺封号，几乎都源于"设备关联"。平台并不只看你的登录账号，而是把设备指纹、网络出口、行为节奏拼成一张关系图谱——任意两家店铺在图谱上"撞车"，风控就会判定为同一主体并连坐处理。' },
      { k: 'h2', t: '关联是怎么被识别的' },
      { k: 'p', t: '最常见的三类信号是硬件指纹（IMEI、Android ID、GAID、分辨率与字体列表）、网络指纹（出口 IP、时区、语言、运营商）以及行为指纹（登录时间、操作习惯、支付方式）。模拟器与改机软件能伪造前两类，却很难持续一致地伪造第三类。' },
      { k: 'h2', t: '云手机环境下的隔离实践' },
      { k: 'p', t: '每家店铺应当对应一台独立云手机 + 一个长期绑定的住宅 IP，二者 1:1 永不混用。设备的时区、语言、键盘要与 IP 所在地一致，避免"美国 IP + 中文系统"这种自相矛盾的组合。' },
      { k: 'ul', items: ['一店一机一 IP，长期绑定不轮换', '系统时区 / 语言 / 键盘与 IP 归属地对齐', '不同店铺错开登录与发货的时间节奏', '支付与收款信息按店铺严格隔离'] },
      { k: 'p', t: '把这套隔离固化成开店 checklist，新店上线照表执行。我们在 200+ 真实店铺上跟踪三个月，关联封禁率从 7.4% 降到接近 0。' },
    ],
    'control-center-v3-recipe': [
      { k: 'p', t: '群控台 V3 的核心只有一句话：把一次人工操作录成脚本，回放到任意分组的上千台设备。过去需要一个人点一天的批量任务，现在压缩成一次点击。' },
      { k: 'h2', t: '录制一个真实工作流' },
      { k: 'p', t: '以"批量更新主页 Banner"为例：在主控设备上手动完成一次——打开 App、进入资料页、上传图片、保存。录制器会把每一步抽象成可参数化的动作，图片路径、文案等字段自动识别为变量。' },
      { k: 'ul', items: ['在主控机录制一次完整操作', '把易变字段标记为变量（图片、文案、链接）', '选择目标分组并映射每台设备的变量来源', '灰度回放 10 台验证无误，再全量执行'] },
      { k: 'h2', t: '回放要像真人' },
      { k: 'p', t: '回放时支持并发度、随机延迟与失败重试，避免"同一秒一千台做同样动作"被风控盯上。失败设备会自动进入重试队列并单独告警。一个 600 账号的 IG 矩阵，过去换 Banner 要两名运营忙一上午，现在一次回放 8 分钟跑完。' },
    ],
    'residential-ip-quality': [
      { k: 'p', t: '"住宅 IP"是个被滥用的词。同样标榜住宅级，有的能稳定养号半年，有的一上号就触发验证码。我们用统一方法横扫了 12 家供应商，给出一份选型矩阵。' },
      { k: 'h2', t: '我们怎么测的' },
      { k: 'p', t: '在 6 个主流平台（TikTok、Instagram、Amazon、Shopee、WhatsApp、Telegram）上各分配同样数量的新号，绑定不同供应商的 IP，连续 30 天执行相同的养号脚本，记录验证码触发率、封禁率与解封比例。' },
      { k: 'h2', t: '关键结论' },
      { k: 'p', t: '价格与质量并不线性相关。最贵的一家解封比例反而垫底，因为其 IP 池被多家代理商转售、复用率过高。真正干净的 IP 来自真实家庭宽带，且每个 IP 的并发用户数被严格限制。' },
      { k: 'ul', items: ['看复用率而非单价：独享 > 轮换 > 共享', '看 ASN 是否为真实民用运营商', '看是否支持粘性会话（长期绑定同一 IP）', '看 IP 池的地理颗粒度（到城市级更佳）'] },
      { k: 'p', t: '最终我们把"独享住宅 + 城市级定位 + 粘性会话"作为内置 IP 池的标准，这也是账号存活率的地基。' },
    ],
    'matrix-account-survival': [
      { k: 'p', t: '1000+ 账号的矩阵能不能活，七成在"开号前"就决定了。设备、网络、内容三层只要有一层偷懒，养得再勤也救不回来。' },
      { k: 'h2', t: '三层地基' },
      { k: 'p', t: '设备层要求每个账号独立指纹、长期不变；网络层要求 IP 与账号 1:1 且地理一致；内容层要求每个账号有差异化的头像、简介与发布节奏，避免"流水线痕迹"。' },
      { k: 'h2', t: '六个标准动作' },
      { k: 'ul', items: ['新号前 7 天只浏览不发布，模拟真实用户', '发布时间随机化，避开整点与批量时刻', '头像 / 简介 / 昵称按人设差异化，禁止复制粘贴', '互动先于发布，建立正常行为基线', '同矩阵账号互不关注、互不跳转', '掉号立即隔离，排查指纹与 IP 再复用'] },
      { k: 'p', t: '把这六条写进 SOP 并用群控台固化执行，我们观察到的 90 天存活率从行业平均的 30% 左右提升到 90%+。存活率每提升 10 个百分点，矩阵的有效产能就接近翻倍——这才是矩阵运营真正的杠杆。' },
    ],
    'openapi-v2-webhook': [
      { k: 'p', t: 'OpenAPI v2 把云手机变成了你自动化流水线里的一等公民。这篇用 50 行 Python，把 Gloryphone、n8n 与 Telegram 串成一个事件驱动的小系统。' },
      { k: 'h2', t: '事件驱动范式' },
      { k: 'p', t: '与其轮询设备状态，不如让设备主动推事件。开机完成、应用崩溃、IP 切换、任务结束都会触发 Webhook，你的服务只需在回调里决定下一步。' },
      { k: 'h2', t: '50 行串起来' },
      { k: 'p', t: '用 REST 接口批量开机并安装目标 App，注册一个 Webhook 指向 n8n；n8n 收到"任务完成"事件后调用 Telegram Bot 推送结果，失败则自动重新下发任务。' },
      { k: 'ul', items: ['POST /devices/batch 批量开机', 'POST /apps/install 安装应用', 'POST /webhooks 订阅设备事件', '在 n8n 中编排：事件 → 判断 → 通知 / 重试'] },
      { k: 'p', t: '整套逻辑没有一行轮询代码，延迟从分钟级降到秒级，运维同学终于可以睡个整觉。' },
    ],
    'byod-zero-data-on-device': [
      { k: 'p', t: '"员工自带设备访问公司系统，敏感数据真能做到 0 落本地吗？"我们用一台真实 Android 手机做了实测，结论比想象中乐观，但有前提。' },
      { k: 'h2', t: '数据会留在哪' },
      { k: 'p', t: '传统 BYOD 方案里，App 缓存、截图、剪贴板、WebView 本地存储都会在手机上留下痕迹，离职擦除往往擦不干净。真正的风险不是主存储，而是这些边角。' },
      { k: 'h2', t: '云手机方案' },
      { k: 'p', t: '把企业 App 全部跑在云端云手机里，本地只保留一个"显示器"——画面是视频流，输入是指令流，文件永不落地。员工手机上没有任何业务数据，离职只需回收云端访问权。' },
      { k: 'ul', items: ['业务 App 全部云端运行，本地仅渲染画面', '剪贴板 / 文件 / 截图按策略禁用或留云端', '会话级水印与操作审计，可追溯到人', '离职一键回收，无需远程擦除个人手机'] },
      { k: 'p', t: '实测一周后对手机做取证，未发现任何业务数据残留。BYOD 的"0 落本地"是可以做到的，前提是把计算搬到云上、把本地降级成纯显示。' },
    ],
    'android-arm-native-perf': [
      { k: 'p', t: '云手机跑得快不快，根子在底层是"ARM 原生"还是"x86 翻译"。我们用三款主流手游加 GeekBench，量化了两条路线的真实差距。' },
      { k: 'h2', t: '翻译层的代价' },
      { k: 'p', t: '在 x86 服务器上跑 Android，需要把 ARM 指令实时翻译成 x86，CPU 要额外做一遍"同声传译"。结果是单核分数缩水、帧率波动、功耗陡增，重载场景尤其明显。' },
      { k: 'h2', t: '实测数据' },
      { k: 'p', t: '同等配置下，ARM 原生节点的 GeekBench 单核领先约 35%，三款手游的平均帧率高出 20–40%，且帧时间方差更小、发热更低。翻译方案在过场动画与多开时最容易掉帧。' },
      { k: 'ul', items: ['GeekBench 单核：ARM 原生领先约 35%', '手游平均帧率：高出 20–40%', '帧时间方差更小，体感更稳', '同负载功耗更低，可堆更高并发'] },
      { k: 'p', t: '对需要长时间稳定运行、或多开挂机的业务，ARM 原生不是"更好一点"，而是"能不能用"的分水岭。' },
    ],
    'tiktok-live-from-cloud': [
      { k: 'p', t: '用云手机做 TikTok 直播，平台到底能不能识别出"这不是真手机"？我们把云手机推流接进直播间，从设备识别测到画面延迟，做了一次完整对比。' },
      { k: 'h2', t: '平台看的是什么' },
      { k: 'p', t: '直播场景里，平台不仅校验设备指纹与 IP，还会分析推流的编码特征、摄像头 / 麦克风的硬件回报，以及网络抖动。云手机若用纯软件虚拟摄像头，最容易在"硬件回报"这一环露馅。' },
      { k: 'h2', t: '怎么做才稳' },
      { k: 'p', t: '关键是让音视频链路看起来像真机：使用设备级虚拟摄像头而非应用级注入，码率与分辨率贴合机型档位，IP 选择与直播受众同地区的住宅出口，避免跨洲高延迟。' },
      { k: 'ul', items: ['设备级虚拟摄像头，提供合理的硬件回报', '码率 / 分辨率匹配机型档位，不要过高', '住宅 IP 与目标受众同地区，降低延迟', '开播前充分养号，账号有正常历史行为'] },
      { k: 'p', t: '在这套配置下连续直播一周，未触发设备异常风控；端到端延迟控制在可接受范围，互动体验与真机几乎无差。' },
    ],
    'ci-cd-android-farm': [
      { k: 'p', t: '把云手机农场接进 GitHub Actions，过去一整晚的 50 机型回归，现在能在一次 CI 内 5 分钟跑完。秘密是 ADB-over-WebSocket 加矩阵任务。' },
      { k: 'h2', t: '直连每一台设备' },
      { k: 'p', t: '云手机通过 ADB-over-WebSocket 暴露调试端口，CI runner 无需本地真机，直接 adb connect 到云端设备，安装 APK、跑 Espresso / UIAutomator、抓日志与截图，全程标准 adb 协议。' },
      { k: 'h2', t: '用矩阵并行' },
      { k: 'p', t: '在 workflow 里用 matrix 维度列出目标机型与 Android 版本，每个组合并行连一台云手机执行同一套用例。50 个组合同时跑，墙钟时间约等于最慢的单台，而不是相加。' },
      { k: 'ul', items: ['云端设备通过 ADB-over-WebSocket 暴露', 'matrix 列出机型 × Android 版本组合', '每个组合并行执行同一套用例', '失败用例自动留存日志 / 截图 / 录屏'] },
      { k: 'p', t: '回归从"提交后等一晚"变成"PR 里几分钟出结果"，开发者当场就能看到兼容性红绿灯，这才是真正可用的移动端 CI。' },
    ],
  },
  en: {
    'tiktok-shop-compliance-2026': [
      { k: 'p', t: 'Almost every multi-store ban on TikTok Shop traces back to "device association". The platform doesn\'t just look at your login — it stitches device fingerprint, network exit and behavioural rhythm into a relationship graph. The moment two of your stores collide on that graph, risk control treats them as one entity.' },
      { k: 'h2', t: 'How association is detected' },
      { k: 'p', t: 'The three usual signal classes are hardware fingerprint (IMEI, Android ID, GAID, resolution, font list), network fingerprint (exit IP, timezone, language, carrier) and behavioural fingerprint (login times, gestures, payment methods). Emulators and device-changers can fake the first two, but rarely keep the third consistent over time.' },
      { k: 'h2', t: 'An isolation playbook for cloud phones' },
      { k: 'p', t: 'Each store should map to one dedicated cloud phone plus one permanently bound residential IP — 1:1 and never shared. The device timezone, language and keyboard must match the IP\'s location; avoid self-contradicting combos like a US IP on a Chinese system.' },
      { k: 'ul', items: ['One store ↔ one phone ↔ one IP, bound long-term', 'Align system timezone / language / keyboard with the IP region', 'Stagger login and fulfilment rhythm across stores', 'Keep payout and payment details isolated per store'] },
      { k: 'p', t: 'Freeze this into a store-launch checklist and run every new store against it. Across 200+ real stores tracked for three months, association bans fell from 7.4% to near zero.' },
    ],
    'control-center-v3-recipe': [
      { k: 'p', t: 'Control Center V3 boils down to one sentence: record a manual operation once, replay it across thousands of devices in any group. A bulk task that used to take a person all day is now a single click.' },
      { k: 'h2', t: 'Recording a real workflow' },
      { k: 'p', t: 'Take "update the profile banner in bulk". On the master device you do it once by hand — open the app, go to the profile, upload the image, save. The recorder abstracts each step into a parameterisable action, auto-detecting fields like image path and copy as variables.' },
      { k: 'ul', items: ['Record one full pass on the master device', 'Mark volatile fields as variables (image, copy, link)', 'Pick the target group and map each device\'s variable source', 'Canary-replay 10 devices, verify, then run the full batch'] },
      { k: 'h2', t: 'Replay like a human' },
      { k: 'p', t: 'Replay supports concurrency, random delay and retries, so you avoid "a thousand devices doing the same thing in the same second" tripping risk control. Failed devices drop into a retry queue with their own alert. For a 600-account IG matrix, swapping the banner used to tie up two operators for a morning; now one replay finishes in 8 minutes.' },
    ],
    'residential-ip-quality': [
      { k: 'p', t: '"Residential IP" is an abused term. Two providers both claim residential grade, yet one warms accounts for six months while the other trips a captcha on first login. We swept 12 vendors with one method and built a selection matrix.' },
      { k: 'h2', t: 'How we tested' },
      { k: 'p', t: 'Across six platforms (TikTok, Instagram, Amazon, Shopee, WhatsApp, Telegram) we assigned the same number of fresh accounts, bound each to a different vendor\'s IPs, and ran an identical warm-up script for 30 days — logging captcha rate, ban rate and unblock ratio.' },
      { k: 'h2', t: 'The takeaways' },
      { k: 'p', t: 'Price and quality aren\'t linear. The most expensive vendor had the worst unblock ratio, because its pool was resold across brokers and over-reused. Genuinely clean IPs come from real home broadband with a hard cap on concurrent users per IP.' },
      { k: 'ul', items: ['Reuse ratio over price: dedicated > rotating > shared', 'Check the ASN is a real consumer ISP', 'Require sticky sessions (bind one IP long-term)', 'Prefer city-level geo granularity'] },
      { k: 'p', t: 'We standardised on "dedicated residential + city-level geo + sticky sessions" for our built-in pool — the bedrock of account survival.' },
    ],
    'matrix-account-survival': [
      { k: 'p', t: 'Whether a 1000+ account matrix survives is 70% decided before the first account is created. Slack off on any of the three layers — device, network, content — and no amount of diligent warming will save it.' },
      { k: 'h2', t: 'Three foundations' },
      { k: 'p', t: 'The device layer needs a unique, stable fingerprint per account; the network layer needs IP-to-account 1:1 with matching geography; the content layer needs differentiated avatars, bios and posting rhythms to avoid an assembly-line footprint.' },
      { k: 'h2', t: 'Six standard moves' },
      { k: 'ul', items: ['First 7 days: browse only, no posting — mimic a real user', 'Randomise posting times; avoid on-the-hour and batch moments', 'Differentiate avatar / bio / handle per persona — never copy-paste', 'Engage before posting to set a normal behaviour baseline', 'Accounts in one matrix never follow or cross-link each other', 'Quarantine a flagged account immediately; re-check fingerprint and IP before reuse'] },
      { k: 'p', t: 'Baked into an SOP and enforced through Control Center, we saw 90-day survival rise from an industry-typical ~30% to 90%+. Every 10-point gain in survival nearly doubles the matrix\'s effective output — that\'s the real lever in matrix ops.' },
    ],
    'openapi-v2-webhook': [
      { k: 'p', t: 'OpenAPI v2 makes the cloud phone a first-class citizen in your automation pipeline. Here\'s a 50-line Python sketch wiring Gloryphone, n8n and Telegram into a small event-driven system.' },
      { k: 'h2', t: 'The event-driven pattern' },
      { k: 'p', t: 'Instead of polling device state, let devices push events. Boot complete, app crash, IP switch, task finished — each fires a webhook, and your service just decides the next step in the callback.' },
      { k: 'h2', t: 'Wiring it in 50 lines' },
      { k: 'p', t: 'Use the REST API to batch-boot and install the target app, then register a webhook pointing at n8n. When n8n receives a "task done" event it calls a Telegram bot to push the result, and re-dispatches the task on failure.' },
      { k: 'ul', items: ['POST /devices/batch to boot in bulk', 'POST /apps/install to install the app', 'POST /webhooks to subscribe to device events', 'Orchestrate in n8n: event → decision → notify / retry'] },
      { k: 'p', t: 'Not a single line of polling, latency drops from minutes to seconds, and your on-call engineer finally sleeps through the night.' },
    ],
    'byod-zero-data-on-device': [
      { k: 'p', t: '"Can sensitive data really leave zero trace on an employee\'s own device when they access company systems?" We ran a field test on a real Android phone. The answer is more optimistic than expected — with one precondition.' },
      { k: 'h2', t: 'Where data lingers' },
      { k: 'p', t: 'In traditional BYOD, app caches, screenshots, clipboard and WebView local storage all leave traces on the phone, and offboarding wipes rarely clean them fully. The real risk isn\'t main storage — it\'s these edges.' },
      { k: 'h2', t: 'The cloud-phone approach' },
      { k: 'p', t: 'Run every corporate app inside a cloud phone; the device keeps only a "display" — pixels are a video stream, input is a command stream, files never touch local disk. There\'s no business data on the phone, so offboarding just revokes cloud access.' },
      { k: 'ul', items: ['Apps run in the cloud; the device only renders pixels', 'Clipboard / file / screenshot disabled or kept cloud-side by policy', 'Per-session watermark and audit log, traceable to a person', 'One-click offboarding — no remote wipe of a personal phone'] },
      { k: 'p', t: 'After a week we forensically imaged the phone and found no residual business data. Zero-on-device BYOD is achievable — provided you move compute to the cloud and demote the device to a pure display.' },
    ],
    'android-arm-native-perf': [
      { k: 'p', t: 'Whether a cloud phone feels fast comes down to one thing underneath: ARM-native vs x86 translation. We quantified the gap with three popular mobile games plus GeekBench.' },
      { k: 'h2', t: 'The cost of a translation layer' },
      { k: 'p', t: 'Running Android on x86 servers means translating ARM instructions to x86 on the fly — the CPU does a round of "simultaneous interpretation". The result is lower single-core scores, jittery frame rates and a spike in power draw, worst under heavy load.' },
      { k: 'h2', t: 'The numbers' },
      { k: 'p', t: 'At equal specs, the ARM-native node leads GeekBench single-core by ~35%, runs the three games 20–40% faster on average, with lower frame-time variance and less heat. Translation stutters most during cutscenes and multi-boxing.' },
      { k: 'ul', items: ['GeekBench single-core: ARM-native ~35% ahead', 'Average game FPS: 20–40% higher', 'Lower frame-time variance — steadier feel', 'Lower power at equal load — pack more concurrency'] },
      { k: 'p', t: 'For workloads that run long or multi-box around the clock, ARM-native isn\'t "a bit better" — it\'s the line between usable and not.' },
    ],
    'tiktok-live-from-cloud': [
      { k: 'p', t: 'Can TikTok tell a cloud phone "isn\'t a real device" during a live stream? We piped a cloud phone\'s stream into a live room and measured everything from device detection to latency.' },
      { k: 'h2', t: 'What the platform checks' },
      { k: 'p', t: 'For live, the platform validates device fingerprint and IP, but also analyses the stream\'s encoding signature, camera / mic hardware reporting and network jitter. A purely software virtual camera is where cloud phones most easily give themselves away.' },
      { k: 'h2', t: 'Doing it reliably' },
      { k: 'p', t: 'The key is making the A/V chain look like a real device: a device-level virtual camera rather than app-level injection, bitrate and resolution matched to the model tier, and a residential IP in the same region as your audience to avoid cross-continent latency.' },
      { k: 'ul', items: ['Device-level virtual camera with plausible hardware reporting', 'Match bitrate / resolution to the model tier — not too high', 'Residential IP in the audience\'s region to cut latency', 'Warm the account well so it has a normal history'] },
      { k: 'p', t: 'With this setup we streamed for a week with no device-anomaly flags; end-to-end latency stayed acceptable and the experience was near-indistinguishable from a real phone.' },
    ],
    'ci-cd-android-farm': [
      { k: 'p', t: 'Plug a cloud-phone farm into GitHub Actions and an overnight 50-device regression finishes in 5 minutes inside one CI run. The trick is ADB-over-WebSocket plus matrix jobs.' },
      { k: 'h2', t: 'Direct to every device' },
      { k: 'p', t: 'Cloud phones expose their debug port over ADB-over-WebSocket, so the CI runner needs no local hardware — it just `adb connect`s to the cloud device, installs the APK, runs Espresso / UIAutomator and pulls logs and screenshots, all over standard adb.' },
      { k: 'h2', t: 'Parallelise with a matrix' },
      { k: 'p', t: 'In the workflow, list target models and Android versions as matrix dimensions; each combination connects to its own cloud phone and runs the same suite in parallel. Run 50 combos at once and wall-clock ≈ the slowest single device, not the sum.' },
      { k: 'ul', items: ['Cloud devices exposed via ADB-over-WebSocket', 'Matrix lists model × Android-version combos', 'Each combo runs the same suite in parallel', 'Failed cases auto-retain logs / screenshots / recordings'] },
      { k: 'p', t: 'Regression goes from "wait overnight" to "results in minutes on the PR" — developers see the compatibility red/green right there. That\'s mobile CI that actually gets used.' },
    ],
  },
}

export type GpContent = (typeof GP_CONTENT)['en']

/**
 * Returns the full content object for the active locale, plus the raw locale.
 * Mirrors the reference design's `useApp().t`.
 */
export function useGp() {
  const { locale } = useI18n()
  const t = computed<GpContent>(() => (GP_CONTENT as any)[locale.value] ?? GP_CONTENT.en)
  const bodies = computed<Record<string, ArticleBlock[]>>(
    () => (GP_ARTICLE_BODIES as any)[locale.value] ?? GP_ARTICLE_BODIES.en,
  )
  return { t, bodies, locale }
}
